export const APP_TYPES = {
  GET_CATEGORIES_REQUEST: 'APP_TYPES.GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'APP_TYPES.GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAIL: 'APP_TYPES.GET_CATEGORIES_FAIL',
  GET_CATS_REQUEST: 'APP_TYPES.GET_CATS_REQUEST',
  GET_CATS_SUCCESS: 'APP_TYPES.GET_CATS_SUCCESS',
  GET_CATS_FAIL: 'APP_TYPES.GET_CATS_FAIL',
  LOAD_MORE_CATS_REQUEST: 'APP_TYPES.LOAD_MORE_CATS_REQUEST',
  LOAD_MORE_CATS_SUCCESS: 'APP_TYPES.LOAD_MORE_CATS_SUCCESS',
  LOAD_MORE_CATS_FAIL: 'APP_TYPES.LOAD_MORE_CATS_FAIL',
}